// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/RKDrive.h"
#include "Commands/Roll.h"
#include "Commands/RotateArm.h"
#include "Commands/Shoot.h"
#include "Commands/Shove.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    opStick.reset(new frc::Joystick(1));
    
    collectCargoButton.reset(new frc::JoystickButton(opStick.get(), 7));
    collectCargoButton->WhileHeld(new Roll(0));
    shootCargoButton.reset(new frc::JoystickButton(opStick.get(), 8));
    shootCargoButton->WhileHeld(new Shoot());
    driveStick.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Shove", new Shove());
    frc::SmartDashboard::PutData("Shoot", new Shoot());
    frc::SmartDashboard::PutData("Roll: default", new Roll(0));
    frc::SmartDashboard::PutData("RotateArm: speed", new RotateArm(0));
    frc::SmartDashboard::PutData("RKDrive", new RKDrive());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriveStick() {
   return driveStick;
}

std::shared_ptr<frc::Joystick> OI::getOpStick() {
   return opStick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
