// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc571.IntialAttempt.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc571.IntialAttempt.subsystems.*;

/**
 *
 */
public class AutoSidePrep extends CommandGroup {

    public AutoSidePrep() {
        /******* addSequential(new WaitCommand(1)); *******/
        addSequential(new TimedForward(1, 0, 0.7));
        addSequential(new CurveTo(25, 0.6, 2, false)); // (float targetAngle, double speed, double radius, boolean toLeft)
        addSequential(new TimedForward(0.8, 25));
    } 
}